In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

Importing the data set and slicing them


In [2]:
data = pd.read_csv(r"C:\Users\sanid\OneDrive\Desktop\machine-learning-full\data preporcessing\Data.csv")

In [3]:
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [4]:
X_features = data.iloc[:, :-1].values # takes index of rows and columns  (all rows and all columns till the last column)
Y_dependent = data.iloc[:, -1].values #only last columns

In [5]:
print(X_features)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Taking care of missing data

In [6]:
from sklearn.impute import SimpleImputer #salary has a missing value to we replacing it with average of the salary
imputer = SimpleImputer(missing_values=np.nan,strategy="mean") # stratergy can be median or anything else bbut mean is recommended
imputer.fit(X_features[:, 1:3]) # look for missing values which is a no not text so all rows and column age n salaray
X_features[:, 1:3] = imputer.transform(X_features[:, 1:3]) #updated values

In [7]:
print(X_features)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


HANDLING CATEGORICAL DATA

encoding indepnedant variable


using one hot encoding for categorical variables just each vector for each category

column transformer params in this format -  transformers=[('encoder',OneHotEncoder(),[0])],  remainder=
Key Parameters:
transformers: List of tuples (name, transformer, columns) where:

name: Identifier for the transformer.

transformer: Transformer object (e.g., OneHotEncoder, StandardScaler).

columns: Columns to apply the transformer (can be column names or indices).

remainder:

'drop' (default): Discard columns not specified in transformers.

'passthrough': Keep remaining columns unchanged.


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')

X_features=np.array(ct.fit_transform(X_features))  #outputs the new matrix of few features with one hot encoding the country column
# doesnt return as a numpy array so we gotta explicitly do it 


In [9]:
print(X_features)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


ENCODING DEPNEDANT VARIABLE USING LABEL ENCODER


In [10]:
from sklearn.preprocessing import LabelEncoder # for 2 categories
le = LabelEncoder()
Y_dependent = le.fit_transform(Y_dependent) # dont need to convert to np array cause we r predicting this

In [11]:
print(Y_dependent)

[0 1 0 0 1 1 0 1 0 1]


SPLITTING THE DATA INTO TEST AND TRAIN

In [12]:
from sklearn.model_selection import train_test_split #format expected for future ml models to predict x_test in the end
X_train,X_test,Y_train,Y_test = train_test_split(X_features,Y_dependent,test_size=0.2,random_state=1) #fixing seed for same split as tutoarial in udemy

In [13]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [14]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [15]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [16]:
print(Y_test)

[0 1]


featurre scaling (used for some model only)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [18]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [19]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
